name: gitlab_api
description: Package project for GitLab API
version: 0.0.1
homepage: https://github.com/bytecrumbs/gitlab_api

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.2.3
  freezed_annotation: ^0.12.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.4
  freezed: ^0.12.1
  build_runner: ^1.10.0
